//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string BookCover { get; set; }
        public int UDC { get; set; }
        public string Title { get; set; }
        public int PageCount { get; set; }
        public string Publisher { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<int> PublishYear { get; set; }
        public string Format { get; set; }
        public Nullable<decimal> FileSize { get; set; }
        public string ListOfAuthors { get; set; }
        public int AuthorID { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
